### ISSUE TITLE
EFT Payment form hyperlink is 404

### ISSUE THREAD

**Issue by gjlawran** [BCDevExchange/code-with-us#1]
The hyperlink from "this form"  is broken.

Then, to get set up to receive an EFT payment, you’ll need to complete [this form](http://www2.gov.bc.ca/assets/gov/family-and-social-supports/child-care/direct_deposit_application.pdf)  and mail it to the opportunity contact with either a VOID cheque or bank stamp. (The good news is, once you’ve done this once, you’ll be all set up to receive direct deposits for any future work you do for the Province of B.C.)

**Comment by mark-a-wilson** [comment]
updated link. Thanks for the alert, @gjlawran !
