### ISSUE TITLE
Are these opportunities open to people who are not B.C Residents?

### ISSUE THREAD

**Issue by panickervinod** [BCDevExchange/code-with-us#2]
Can people residing outside B.C participate in these challenges?

**Comment by mark-a-wilson** [comment]
Absolutely! However, you will notice that some opportunities have in-person requirements as part of the Acceptance Criteria, while others do not and can be fulfilled remotely. 

Thanks for reaching out!

**Comment by panickervinod** [comment]
@mark-a-wilson  Thank you for clarifying !!
