### ISSUE TITLE
LICENSE File mising

### ISSUE THREAD

**Issue by agehlers** [BCDevExchange/code-with-us#3]
Hi, could you please add a LICENSE file your repo. All repositories in the BCGOV ORG are required to have a LICENSE file. Reference: https://github.com/bcgov/BC-Policy-Framework-For-GitHub/tree/master/BC-Gov-Org-HowTo and https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Cheatsheet.md. Thank you.

**Comment by mark-a-wilson** [comment]
https://github.com/BCDevExchange/code-with-us/commit/a8dc1ae3b02cad298a8c22085eb1a54bb9e2bdfa
