### ISSUE TITLE
Question: broader public sector use of CWU

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/code-with-us#5]
Can broader public sector organizations use the existing _Code With Us_ terms to pay for code?

**Comment by mark-a-wilson** [comment]
The way I understand the [terms](https://github.com/BCDevExchange/code-with-us/blob/master/Code%20With%20Us%20Terms_2018-01-23.pdf), they can be used without modification as long as the "Issuer" is the Province or a Public Sector Entity?

**Comment by ZachWoodward** [comment]
This is correct, the Code With Us terms identify that the 'Issuer' must be either the Province or a Public Sector Entity. So long as the opportunity poster falls within those two groups, there should be no concerns.

**Comment by mark-a-wilson** [comment]
Thanks for confirming.
